# -*- coding: utf-8 -*-
"""graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11OcBFsLzxQrapcRoNpnX6lyHVGc7YtuB
"""

import matplotlib.pyplot as plt

hours=[1,2,3,4,5,6,7,8]
visitors=[50,60,65,70,90,120,110,130]
plt.plot(hours,visitors,
         color="red",
         marker="o",
         linestyle="-",
         linewidth=1,
         alpha=1,
         label="Visitors")
plt.title("website visitors Per Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Number of Visitors")
plt.legend()
plt.grid(True,linestyle="-",alpha=0.6)
plt.show()

import matplotlib.pyplot as plt
products=["Laptop","Mobile","Table","Headphones","Smartwatch"]
sales=[250,400,150,300,180]
plt.bar(products,sales,color="green",edgecolor="red",alpha=0.5,width=0.5)
plt.title("Product Sales Comparision")
plt.xlabel("Products")
plt.ylabel("Units sold")
plt.show()

import matplotlib.pyplot as plt
marks=[45,68,45,87,98,56,84,56,87,65,
       98,76,54,32,21,12,34,56,78,90,
       54,89,89,78,76,58,46,24,31,55]
plt.hist(marks,bins=10,histtype='bar',edgecolor='black')
plt.title("Dstibution of Student Marks")
plt.xlabel("Marks Range")
plt.ylabel("Number of Students")
plt.show()

import matplotlib.pyplot as plt

brands = ["Apple", "Samsung", "Xiaomi", "Oppo", "Others"]
market_share = [30, 25, 20, 10, 15]

plt.pie(
    market_share,
    labels=brands,
    autopct="%.2f%%",
    startangle=0,
    colors=["gold", "skyblue", "lightgreen", "green", "violet"],
    explode=[0.1, 0, 0, 0, 0],
    shadow=True
)

plt.title("Mobile Market Share")
plt.show()

import matplotlib.pyplot as plt

scores = [
    [56,78,56,34,76,76,78,98],
    [23,54,78,87,56,43,12,21],
    [23,43,54,57,95,38,20,41],
    [61,20,31,50,91,82,73,33],
    [23,71,90,74,62,37,10,99]
]

# Transpose the data - REMOVED THIS LINE
# scores = list(map(list, zip(*scores)))

plt.boxplot(
    scores,
    patch_artist=True,
    boxprops=dict(facecolor="lightblue"),
    medianprops=dict(color="red", linewidth=2),
    whiskerprops=dict(color="green"),
    capprops=dict(color="black"),
    notch=False,
    vert=True,
    tick_labels=["A", "B", "C", "D", "E"]
)

plt.title("Exam Scores Distribution Across Classes")
plt.xlabel("Classes")
plt.ylabel("Scores")
plt.grid(True, linestyle="--", alpha=0.7)

plt.show()

import matplotlib.pyplot as plt
days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
visitors=[120,150,170,200,180,220,250]
plt.fill_between(days,visitors,
                 color="skyblue",alpha=0.5,
                 label="Website Visitors")
plt.plot(days,visitors,color="blue",linewidth=1)
plt.title("Website Visitors Over a Week")
plt.xlabel("Day of Week")
plt.ylabel("Number of Visitors")
plt.legend()
plt.grid(True,linestyle="-",alpha=0.6)
plt.show()