# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CI-ou9vsXHPURzx8h7BDR6u0qzQD-tJl
"""

import numpy as np
arr1=np.array([1,2,3,4,5])
print("1-dim",arr1,sep='\n',end='\n\n')

arr2=np.array([[1,2,3],[4,5,6]])
print("2-dim",arr2,sep='\n',end='\n\n')

arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("multi-dim",arr3,sep='\n')

zeros=np.zeros((3,4))
print(zeros)

ones=np.ones((3,4))
print(ones)

identity=np.eye(7)
print(identity)

full_array=np.full((2,3),100)
print(full_array)

range_arr=np.arange(1,30,2)
print(range_arr)

lin_space=np.linspace(50,100,6)
print(lin_space)

np.random.seed(10)
rand_arr=np.random.randint(6)
print(rand_arr)

rand_int=np.random.randint(30,60)
print(rand_int)

rand_int=np.random.randint(1,6,(5,5)))
print(rand_int)

rand_float=np.random.rand(3,2)
print(rand_float)

rand_int=np.random.randint(1,6,(5,5))
print(rand_int)

l=['html','css','js','python','mysql']
rand_choice=np.random.choice(l,4)
print(rand_choice)

arr=np.array([[1,2],[4,5],[6,7],[8,7],[1,2],[4,5]])
print(arr.shape)

reshaped=arr.reshape(4,3)
print(reshaped)

a=np.array([[1,2,3,4],[1,2,3,4]])
flattened=a.flatten()
print(flattened)

transposed=arr.T
print(transposed)

arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

matrix=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[1,1])
print(matrix[2,1])
print(matrix[0,2])
print(matrix[0:3,0])
print(matrix[0:2,1:3])

arr=np.array([4,9,16,25,36])

print(arr+1)
print(arr*1)
print(arr**2)
print(np.sqrt(arr))

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))





a=np.array([1,2,3,4,5])
print(np.mean(a))
print(np.var(a))
print(np.std(a))

print(np.min(arr))
print(np.max(arr))

arr=np.array([1,2,3,4,5])
print(np.cumsum(arr))
print(np.cumprod(arr))

arr=np.array([10,20,30,40,50])
print(arr%20==0)
print(arr[arr%20==0])

arr=np.array([3,1,4,1,5,9,2,6])
sorted_arr=np.sort(arr)
print(sorted_arr)