# -*- coding: utf-8 -*-
"""numpy2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5xWk4iSU2qXhdoowAf7aq3IWzCscomf
"""

import numpy as np
arr=np.array([10,20,30])
view_arr=arr.view()
view_arr[0]=100
print(arr,view_arr)

copy_arr=arr.copy()
copy_arr[0]=200
print(arr,copy_arr)



A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))

print(np.linalg.det(A))

print(np.linalg.inv(A))

eigenvalues,eigenvectors=np.linalg.eig(A)
print(eigenvalues)

print(eigenvectors)

C=np.array([5,11])
solution=np.linalg.solve(A,C)
print(solution)

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
vertical_stack=np.vstack((A,B))
horizantal_stack=np.hstack((A,B))
print(vertical_stack)
print(horizantal_stack)

split_arr=np.split(np.array([1,2,3,4,5,6]),3)
print(split_arr)